### ISSUE TITLE
Some of these functions and comments are suspiciously familiar :)

### ISSUE THREAD

**Issue by SeanJxie** [mihonen/polynomials#3]
Would have appreciated it if you reached out 👍

**Comment by mihonen** [comment]
My apologies for the oversight. I did indeed use your project in the beginning to get this one started. I will add a mention for this. Let me know if there is something else I can do for you.

**Comment by SeanJxie** [comment]
Appreciate it. I like to see how you've expanded on top of the base library (root finding algorithms, etc.) Keep up the good work 👍

Cheers!
